WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/swiatoi/Desktop/Urban University/module 12/mylogging.py", line 27, in test_run
    runner = Runner("Petr", "grigoriy")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swiatoi/Desktop/Urban University/module 12/rt_with_exceptions.py", line 8, in __init__
    if speed > 0:
       ^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/swiatoi/Desktop/Urban University/module 12/mylogging.py", line 16, in test_walk
    runner = Runner("Petr", speed = -5)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/swiatoi/Desktop/Urban University/module 12/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
